### PR TITLE
Update/packagecloud provider

### PR DESCRIPTION
**Pull request by MWilkinson**
A bit of reworking to switch to using the packagecloud repo for varnish packages

also updates the varnish version matching regexs to handle version 5.0/5.1 of varnish

### CODE REVIEW

**Comment by bashtoni** [comment]
@MWilkinson thanks for this - are you able to rebase against master please?

**Comment by MWilkinson** [comment]
@bashtoni That should have done it

**Comment by craigwatson** [comment]
Thanks @MWilkinson 👍

**Comment by hjstam** [comment]
Thank you @MWilkinson for the patch. However the packagecloud puppet module lacks support of modern operating systems like CentOS 7 or Ubuntu 16/17. I believe it would be better to only change the repositories without using the packagecloud puppet module which isn't being maintained very active.

**Pull request merged**
